[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["npm install -g pnpm", "pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm --filter @echoshq/sdk build"]

[start]
cmd = "cd apps/daemon && pnpm dev"

